### PR TITLE
Updated integration test to use in-memory sql lite db

### PR DESCRIPTION
**Pull request by OmarSemou**

### CODE REVIEW

**Comment by Asger124** [comment]
Looks good! I have two questions for my own understanding. 

1. the third acceptance criteria for the issue linked to this PR states: 'Performance of the test suite improves.' Is this a measurable metric that we can confirm? or is it a consqequence of using in memory testing? hope that makes sense

2. When we use this factory webapplication class i can see that we open a connection to the db.context.database at line: 26, but we never explicitly close or dispose of this connection. Is it handled under the hood so to speak, or should we do it manually ?

Once again, great job

**Comment by Asger124** [comment]
Okay, cool thanks for the extensive answer. 
So just in a very practical sense for our project, the way i would be able to confirm that perfomance has indeed enhanced for our test suite would be to track how much time it takes to execute our tests when running 'dotnet test' ,for example, and then compare  it to how long it took before we switched to in-memory database 
correct ?

**Comment by OmarSemou** [comment]
Yes basically :)

**Comment by Asger124** [comment]
Yeah i figured :) I was just wondering about how it would relate to our project, in a practical sense, but thanks for the answers! i will close the pull request and merge it:)

**Review by Asger124 — APPROVED** [review]

**Pull request merged**
