### PR TITLE
Altered unittests

### PR DESCRIPTION
**Pull request by Asger124**
This PR contains new and altered unit tests. The newly added unittests, are testing the methods CreateCheep(),CreateAuthor(), and also checks number of cheeps per page. Unittests in general now only use the one method that is under test, besides when the need for setup methods. I have also altered return value of CheckAuthorExists(), see commit https://github.com/ITU-BDSA2024-GROUP18/Chirp/commit/96982101dc5582fcdadda887a8c9cf30829814dd, for more detail.

### CODE REVIEW

**Comment by andsji** [comment]
Nice job, the tests you added were missing, so that's perfect.
The commit says several files have been deleted, is this due to the clean-up? If so I assume they would just have been moved and therefore also should be under "files added", but I can't find them - just don't want to merge anything that deletes stuff we need :)

**Comment by OmarSemou** [comment]
Looks great Asger, but would it be possible to fix the warnings? I can see there are two from the unit tests

**Comment by andsji** [comment]
Could also just be because this is a branch from the branch that removed unnecessary files, but shouldn't they then not be included as deleted files here, since they're not on the main branch anyways?

**Comment by Asger124** [comment]
Anders
- Yes the deleted files are from the clean_up commit, since this branch is made from the Clean_up branch that we just merged. All the files that are shown here as deleted, has also been removed from main, when we merged the other PR regarding clean_up. Alternatively i can merge main into this, and then i think the commit regarding the Clean_up(deleted files) will no longer show as files changed i beleive. Hope that answers the question?
Omar 
-Yes of course i will try to resolve them right away

**Comment by Asger124** [comment]
I think i have adressed your concerns with the latest two commits

**Review by OmarSemou — APPROVED** [review]
Thanks for addressing the comments :) nice job

**Review by andsji — APPROVED** [review]
Perfect, answered my questions - looks way cleaner now that main was merged into it, that removes the scariness of possibly deleting files :)

**Pull request merged**
